In [637]:
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt
import numpy as np

In [638]:
import pandas as pd
df=pd.read_csv("catdog.csv")

In [639]:
import cv2
df1=[]
for i in df["images"]:  
    image = cv2.imread(i)
    resized = cv2.resize(image, (32, 32))
    df1.append(resized)
df["Ima"]=df1

In [640]:
from sklearn.model_selection import train_test_split


In [641]:
y=df["output"]

In [642]:
y1=np.array(y).reshape(-1,)

In [643]:
y1

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1], dtype=int64)

In [644]:
type(y1)

numpy.ndarray

In [645]:
x=list(df["Ima"])


In [646]:
type(x)

list

In [647]:
x

[array([[[ 1,  0,  2],
         [ 1,  0,  4],
         [ 1,  0,  4],
         ...,
         [ 1,  0,  9],
         [ 0,  0,  6],
         [ 0,  0,  6]],
 
        [[ 1,  0,  2],
         [ 0,  0,  7],
         [ 0,  0,  6],
         ...,
         [ 0,  1,  5],
         [ 0,  0,  6],
         [ 0,  0,  6]],
 
        [[ 0,  0,  4],
         [ 0,  1,  2],
         [ 0,  0,  6],
         ...,
         [ 0,  0,  8],
         [ 0,  0,  6],
         [ 0,  0,  8]],
 
        ...,
 
        [[19, 27, 40],
         [23, 29, 44],
         [22, 36, 58],
         ...,
         [45, 57, 77],
         [ 0,  0,  1],
         [ 8,  6,  8]],
 
        [[28, 42, 69],
         [ 0,  0,  3],
         [40, 46, 61],
         ...,
         [22, 32, 48],
         [ 0,  1,  3],
         [27, 37, 55]],
 
        [[ 9, 24, 50],
         [27, 38, 56],
         [ 8, 22, 43],
         ...,
         [ 3,  3,  9],
         [65, 74, 88],
         [17, 27, 44]]], dtype=uint8),
 array([[[ 19,   6,  12],
         [ 21,  

In [648]:
x1=x

In [649]:
x1=np.array(x1)

In [650]:
x1

array([[[[  1,   0,   2],
         [  1,   0,   4],
         [  1,   0,   4],
         ...,
         [  1,   0,   9],
         [  0,   0,   6],
         [  0,   0,   6]],

        [[  1,   0,   2],
         [  0,   0,   7],
         [  0,   0,   6],
         ...,
         [  0,   1,   5],
         [  0,   0,   6],
         [  0,   0,   6]],

        [[  0,   0,   4],
         [  0,   1,   2],
         [  0,   0,   6],
         ...,
         [  0,   0,   8],
         [  0,   0,   6],
         [  0,   0,   8]],

        ...,

        [[ 19,  27,  40],
         [ 23,  29,  44],
         [ 22,  36,  58],
         ...,
         [ 45,  57,  77],
         [  0,   0,   1],
         [  8,   6,   8]],

        [[ 28,  42,  69],
         [  0,   0,   3],
         [ 40,  46,  61],
         ...,
         [ 22,  32,  48],
         [  0,   1,   3],
         [ 27,  37,  55]],

        [[  9,  24,  50],
         [ 27,  38,  56],
         [  8,  22,  43],
         ...,
         [  3,   3,   9],
        

In [651]:
x_train,x_test,y_train,y_test=train_test_split(x1,y1,test_size=0.3)


In [652]:
x_train=x_train/255.0
x_test=x_test/255

In [653]:
cnn = models.Sequential([
    layers.Conv2D(filters=32, kernel_size=(3, 3), activation='relu', input_shape=(32, 32, 3)),
    layers.MaxPooling2D((2, 2)),
    layers.Dropout(0.1),
    layers.Conv2D(filters=64, kernel_size=(3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(32,activation='relu'),
    layers.Dropout(0.1),
    layers.Dense(16,activation='relu'),
    layers.Dense(2, activation='softmax')
])

In [654]:
cnn.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [655]:
cnn.fit(x_train, y_train, epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 434ms/step - loss: 0.6689 - accuracy: 0.5714
Epoch 2/10
1/1 [==============================] - 0s 8ms/step - loss: 0.6655 - accuracy: 0.5714
Epoch 3/10
1/1 [==============================] - 0s 14ms/step - loss: 0.6159 - accuracy: 0.5714
Epoch 4/10
1/1 [==============================] - 0s 8ms/step - loss: 0.5661 - accuracy: 0.5714
Epoch 5/10
1/1 [==============================] - 0s 16ms/step - loss: 0.5755 - accuracy: 0.8571
Epoch 6/10
1/1 [==============================] - 0s 16ms/step - loss: 0.4566 - accuracy: 1.0000
Epoch 7/10
1/1 [==============================] - 0s 16ms/step - loss: 0.5058 - accuracy: 0.8571
Epoch 8/10
1/1 [==============================] - 0s 16ms/step - loss: 0.4687 - accuracy: 0.7143
Epoch 9/10
1/1 [==============================] - 0s 16ms/step - loss: 0.4321 - accuracy: 0.8571
Epoch 10/10
1/1 [==============================] - 0s 16ms/step - loss: 0.4300 - accuracy: 0.8571


In [656]:
y_pred = cnn.predict(x_test)
y_pred[:]

1/1 [==============================] - 0s 73ms/step


array([[0.4381269 , 0.5618732 ],
       [0.3405856 , 0.6594144 ],
       [0.32270002, 0.6773    ]], dtype=float32)

In [657]:
y_classes = [np.argmax(element) for element in y_pred]
y_classes[:]

[1, 1, 1]

In [658]:
y_test = y_test.reshape(-1,)

In [659]:
y_test[:]

array([1, 0, 0], dtype=int64)

In [660]:
x1.shape[0]

10